# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [5]:
arr = np.arange(2,20)

In [6]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [7]:
arr.shape

(18,)

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [45]:
#Get a value at an index

In [9]:
arr[6]

8

In [46]:
#Get values in a range

In [10]:
arr[2:6]

array([4, 5, 6, 7])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [12]:
#Setting a value with index range (Broadcasting)
arr[2:6] = 99

In [13]:
arr

array([ 2,  3, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [14]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(2,20)
#Show
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
#Important notes on Slices
slice = arr[2:6]

In [17]:
slice

array([4, 5, 6, 7])

In [18]:
#Change Slice
slice[:] = 99

In [19]:
arr

array([ 2,  3, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

Now note the changes also occur in our original array!

Data is not copied, it's a view of the original array! This avoids memory problems!

In [21]:
#To get a copy, need to be explicit
arr2 = arr.copy()

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [22]:
arr = np.arange(20).reshape(4,5)
#Show
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
#Indexing row
arr[0]

array([0, 1, 2, 3, 4])

In [24]:
# Getting individual element value
arr[1][1]

6

In [25]:
# Getting individual element value
arr[1,1]

6

In [27]:
# 2D array slicing

arr[1:,0:2]

array([[ 5,  6],
       [10, 11],
       [15, 16]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [28]:
#Set up array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Fancy indexing allows the following

In [33]:
arr[[0,3],[1,2]]

array([ 1, 17])

In [37]:
#Allows in any order
arr[:,[3,1,3]]

array([[ 3,  1,  3],
       [ 8,  6,  8],
       [13, 11, 13],
       [18, 16, 18]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection or boolean indexing

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
bool = arr > 10

In [41]:
arr[bool]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])