# NumPy Operations

In [1]:
import numpy as np

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [9]:
arr1 = np.random.normal(2,2,10).reshape(2,5)
arr2 = np.random.normal(2,2,10).reshape(5,2)

In [10]:
arr1

array([[ 2.64716198, -0.30690964,  5.34281053,  3.25893501,  0.28134856],
       [ 3.12743916, -2.57682256,  5.05120392,  5.06534637,  2.29980202]])

In [11]:
arr2

array([[-2.86693154,  3.94421282],
       [ 2.43653846,  5.31684063],
       [ 4.62875412,  2.07480957],
       [ 0.46927239,  3.64542228],
       [ 2.49383894,  2.86636784]])

In [3]:
arr

array([ 2.68069233,  0.72274477,  4.20916402,  0.9227533 ,  0.6406052 ,
       -3.41917771,  3.83011739, -0.20368177, -1.62106152,  0.86384858])

In [4]:
arr + arr

array([ 5.36138466,  1.44548954,  8.41832803,  1.8455066 ,  1.2812104 ,
       -6.83835543,  7.66023479, -0.40736355, -3.24212304,  1.72769715])

In [5]:
arr = arr + 2

array([ 4.68069233,  2.72274477,  6.20916402,  2.9227533 ,  2.6406052 ,
       -1.41917771,  5.83011739,  1.79631823,  0.37893848,  2.86384858])

In [6]:
arr - 3

array([-0.31930767, -2.27725523,  1.20916402, -2.0772467 , -2.3593948 ,
       -6.41917771,  0.83011739, -3.20368177, -4.62106152, -2.13615142])

In [7]:
arr - arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr * arr

array([ 7.18611138,  0.52236   , 17.71706171,  0.85147365,  0.41037502,
       11.69077624, 14.66979925,  0.04148627,  2.62784045,  0.74623436])

In [12]:
arr1 @ arr2

array([[18.62449319, 32.58113774],
       [16.2484627 , 34.17242199]])

In [14]:
arr2 @ arr1

array([[  4.74605347,  -9.28364767,   4.60555121,  10.6356605 ,
          8.26430154],
       [ 23.07800757, -14.44835204,  39.87440957,  34.87215988,
         12.9131974 ],
       [ 18.74190258,  -6.76702535,  35.21084246,  25.59443796,
          6.07394453],
       [ 12.64307643,  -9.53763061,  20.92100477,  19.99465473,
          8.51577863],
       [ 15.56598665,  -8.15150454,  27.80271742,  22.64640498,
          7.29371655]])

In [15]:
a = 1

In [40]:
# Warning on division by zero, but not an error!
# Just replaced with nan


In [17]:
a/0

ZeroDivisionError: division by zero

In [18]:
arr = np.arange(6)

In [20]:
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
# Also warning, but not an error instead infinity


In [21]:
1/arr

C:\Users\M\AppData\Local\Temp\ipykernel_31256\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [22]:
arr1

array([[ 2.64716198, -0.30690964,  5.34281053,  3.25893501,  0.28134856],
       [ 3.12743916, -2.57682256,  5.05120392,  5.06534637,  2.29980202]])

In [23]:
#Taking Square Roots
np.sqrt(arr1)

C:\Users\M\AppData\Local\Temp\ipykernel_31256\1484227506.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)


array([[1.62701013,        nan, 2.31145204, 1.80525206, 0.530423  ],
       [1.76845672,        nan, 2.24748836, 2.25063244, 1.51650982]])

In [24]:
#Calcualting exponential (e^)
np.exp(arr1)

array([[1.41139261e+01, 7.35717080e-01, 2.09099567e+02, 2.60218095e+01,
        1.32491534e+00],
       [2.28154779e+01, 7.60151539e-02, 1.56210416e+02, 1.58435310e+02,
        9.97220796e+00]])

In [25]:
np.sin(arr1)

array([[ 0.47453059, -0.30211413, -0.80777908, -0.11707326,  0.27765144],
       [ 0.01415302, -0.53522162, -0.94314921, -0.93835452,  0.74583711]])

In [26]:
np.log(arr1)

C:\Users\M\AppData\Local\Temp\ipykernel_31256\2108464003.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr1)


array([[ 0.97348811,         nan,  1.67575183,  1.18140046, -1.26816095],
       [ 1.14021451,         nan,  1.61962661,  1.62242252,  0.83282304]])

## Sorting

In [33]:
arr = np.random.randint(1,10,9)

In [43]:
np.random.randint(9,)

0

In [44]:
arr

array([3, 5, 9, 1, 4, 9, 8, 2, 4])

In [45]:
arr.sort()

In [46]:
arr

array([1, 2, 3, 4, 4, 5, 8, 9, 9])

In [55]:
arr1 = np.random.normal(2,2,(2,5))

In [56]:
arr1

array([[-1.44888078, -0.19599446,  4.36306098,  3.70310208,  2.52955084],
       [ 0.92797865,  1.60098396,  0.85616124,  4.16243668,  1.50660403]])

In [57]:
arr1.sort(axis=0)

In [58]:
arr1

array([[-1.44888078, -0.19599446,  0.85616124,  3.70310208,  1.50660403],
       [ 0.92797865,  1.60098396,  4.36306098,  4.16243668,  2.52955084]])